### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vabarbosa** [vabarbosa/Fun-with-Quantum#8]
Overview, descriptions, and instructions need to be updated.

- [x] The [README.md](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/README.md) notebook needs to be reviewed and updated accordingly to fix broken links, typos, etc.

Instructions on how users can run the various notebooks should be separated from the README and documented in a separate GETTING_STARTED document (see #9)

**Comment by oyin-bee** [comment]
Most links are ok
Suggested amendments:
A spectrum of Quantum Computing demos and Serious Games for Quantum Computing (that illustrate superposition, interference and entanglement) will **being** made available on this device for an engaging introduction to Quantum Computing. = be

oberservables = observables

introductions = introduction

https://mybinder.org/v2/gh/JanLahmann/Fun-with-Quantum/master?filepath=Merminâ€“Peres-Game.ipynb = does not load

**Comment by vabarbosa** [comment]
@oyin-bee  i have made the suggested updates. thanks!
